In [6]:
import pandas as pd

In [12]:
df = pd.read_csv('callbacks/vgg16/age/consolidados/history-regression-abordagem9-lrelu.csv')
#df = pd.read_csv('callbacks/squeeze/age/consolidados/history-regression-abordagem-squeeze1-relu.csv')

In [13]:
df.head()

   epoch       loss  mean_squared_error   val_loss  val_mean_squared_error
0      0  13.437821         1815.986529  11.278143              202.741713
1      1  11.335991          214.091833  11.254463              215.566038
2      2  11.325953          213.948862  11.164460              206.331561
3      3  11.324818          213.779372  11.167085              206.912729
4      4  11.303097          213.177162  11.169003              204.772207

In [14]:
df.sort_values('val_loss')

    epoch       loss  mean_squared_error   val_loss  val_mean_squared_error
81     81  11.257184          211.655275  11.159761              205.406160
63     63  11.254924          211.551717  11.159988              205.447511
48     48  11.262952          211.898586  11.160290              205.364671
42     42  11.262065          212.002632  11.160401              205.523534
32     32  11.262523          211.941972  11.160911              205.619126
73     73  11.255665          211.497892  11.160972              205.630531
61     61  11.257135          211.460898  11.161387              205.709830
60     60  11.257811          211.898318  11.161446              205.721194
18     18  11.271615          212.199092  11.161478              205.727340
69     69  11.254346          211.433727  11.161676              205.765645
57     57  11.257955          211.832082  11.161750              205.259626
75     75  11.255630          211.758799  11.161875              205.804334
9       9  11.285588          212.669493  11.161931              205.246752
47     47  11.256486          211.413736  11.162479              205.923617
27     27  11.261895          211.788283  11.162748              205.189162
59     59  11.259854          211.926469  11.162755              205.978749
68     68  11.260337          211.805221  11.163387              205.144586
29     29  11.267359          212.096828  11.163416              206.113272
80     80  11.253679          211.709530  11.163586              206.148335
31     31  11.264898          211.918301  11.163751              205.119394
78     78  11.259252          211.668110  11.164115              205.094412
67     67  11.260004          211.877630  11.164170              205.090610
2       2  11.325953          213.948862  11.164460              206.331561
62     62  11.259256          211.705622  11.165256              206.503006
41     41  11.262752          211.791811  11.165489              206.553989
74     74  11.254226          211.483883  11.165698              206.599990
55     55  11.253000          211.613899  11.166112              206.692013
71     71  11.252786          211.843962  11.166233              204.951595
53     53  11.257905          211.543421  11.166356              206.746736
44     44  11.261113          211.646156  11.166575              206.796339
..    ...        ...                 ...        ...                     ...
38     38  11.263221          211.823774  11.176398              209.345649
35     35  11.263666          211.771733  11.179573              204.165017
28     28  11.263748          211.740678  11.180812              204.101847
72     72  11.254165          211.436836  11.181282              204.078329
13     13  11.278940          212.537426  11.182856              204.001282
66     66  11.257460          211.470031  11.183230              209.949603
22     22  11.275332          212.211226  11.185298              210.089555
51     51  11.260356          211.777707  11.188183              203.760743
45     45  11.261272          212.143933  11.190675              203.658839
34     34  11.260961          211.702636  11.191616              210.525558
33     33  11.259340          212.003002  11.191724              203.618001
54     54  11.259191          211.657503  11.192993              210.622321
56     56  11.259605          211.805689  11.193152              203.564318
43     43  11.263259          211.748414  11.195662              203.475370
46     46  11.261737          211.801732  11.202543              211.310167
14     14  11.287217          212.340396  11.204025              211.419550
26     26  11.263799          211.916664  11.207701              203.212880
15     15  11.286495          212.802991  11.210942              211.939467
16     16  11.276212          212.139983  11.214298              212.197353
40     40  11.258810          211.818844  11.219638              203.105865
30     30  11.265276          211.824722  11.220350              212.671512
24     24  11.272382          212.242207  11.220352              203.100322
17     17  11.273448          212.467171  11.238561              202.991898
11     11  11.286561          212.836691  11.238661              202.991478
19     19  11.269898          212.061452  11.242568              202.976528
1       1  11.335991          214.091833  11.254463              215.566038
0       0  13.437821         1815.986529  11.278143              202.741713
5       5  11.302375          213.141293  11.280236              202.981754
6       6  11.299709          212.823423  11.390387              203.898360
8       8  11.282030          212.323118  11.442112              226.460302

[83 rows x 5 columns]