In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('callbacks/lenet/age/consolidados/history-regression-abordagem-5-relu.csv')

In [3]:
df.head()

   epoch       loss  mean_squared_error   val_loss  val_mean_squared_error
0      0  11.787199          233.384754  10.710873              188.755555
1      1  10.859027          196.642491  10.735814              195.615834
2      2  10.670410          190.323891  10.411555              179.395972
3      3  10.429914          183.181870  10.450142              175.707899
4      4  10.228069          177.723754  10.350632              173.571363

In [5]:
df.sort_values('val_loss')

    epoch       loss  mean_squared_error   val_loss  val_mean_squared_error
8       8   8.982497          144.497288  10.041809              169.135889
10     10   8.333514          129.043272  10.159408              172.480091
7       7   9.380152          154.780732  10.165417              171.931573
12     12   7.518880          110.546965  10.227520              175.328195
9       9   8.643481          136.487242  10.248419              172.061043
6       6   9.636846          160.834759  10.266600              179.352140
13     13   7.129316          101.516772  10.272024              179.202530
14     14   6.712181           92.578281  10.284089              175.912604
4       4  10.228069          177.723754  10.350632              173.571363
2       2  10.670410          190.323891  10.411555              179.395972
3       3  10.429914          183.181870  10.450142              175.707899
15     15   6.403295           85.863299  10.452257              182.584897
17     17   5.595336           69.979195  10.464977              183.150534
16     16   5.951634           76.728821  10.485010              181.302335
19     19   4.870264           57.156911  10.535447              186.001557
5       5   9.879393          167.380730  10.606154              178.363519
18     18   5.239187           63.453913  10.636415              188.745383
20     20   4.680083           52.810015  10.652834              188.662226
23     23   3.930290           40.225224  10.686654              192.978998
0       0  11.787199          233.384754  10.710873              188.755555
1       1  10.859027          196.642491  10.735814              195.615834
27     27   3.138917           28.403649  10.751718              194.452270
47     47   1.917541           12.099016  10.754227              195.806642
26     26   3.366350           31.333932  10.784621              195.391205
28     28   3.056485           26.855643  10.788464              194.219342
59     59   1.538740            9.540860  10.791970              197.122771
95     95   1.178876            7.748363  10.797029              196.817991
99     99   1.164566            7.651731  10.797649              197.332526
32     32   2.753925           21.792802  10.798400              197.091250
24     24   3.722930           37.133081  10.800090              193.543664
..    ...        ...                 ...        ...                     ...
78     78   1.307139            8.225466  10.941075              200.358694
50     50   1.763892           11.007645  10.941269              201.309127
42     42   2.044558           13.600565  10.943730              200.600306
45     45   1.912658           12.410534  10.944446              202.248522
54     54   1.665360           10.276928  10.945514              201.285859
97     97   1.199715            7.790119  10.947356              201.597918
86     86   1.241693            7.976411  10.951491              200.443834
62     62   1.525115            9.320556  10.953916              201.091393
58     58   1.563943            9.610472  10.957399              201.584671
66     66   1.508882            9.198810  10.970359              202.280648
68     68   1.453036            8.829162  10.972735              201.375442
25     25   3.479501           33.615346  10.975452              198.552106
37     37   2.354098           16.821658  10.978083              201.540052
61     61   1.495377            9.192716  10.978533              202.358050
34     34   2.507495           19.077833  10.983160              200.471506
60     60   1.578186            9.584297  10.989221              201.661475
65     65   1.490694            9.089586  10.990797              201.498488
79     79   1.344449            8.408925  11.004762              201.514229
36     36   2.293508           16.892309  11.009263              201.058024
48     48   1.847433           11.649187  11.013718              203.440574
72     72   1.383184            8.607610  11.019983              202.225207
53     53   1.701538           10.541974  11.026931              202.600339
33     33   2.709203           20.844258  11.037965              203.082612
46     46   1.961684           12.444193  11.056741              203.921058
38     38   2.241969           15.814911  11.066354              203.785455
41     41   2.045945           13.820792  11.087804              204.130233
40     40   2.155716           14.685221  11.089377              203.370769
11     11   7.897560          119.059096  11.162417              196.681601
51     51   1.762723           10.886785  11.174915              206.348210
22     22   4.199050           44.361953  11.245676              205.989784

[100 rows x 5 columns]